### ISSUE TITLE
No such file or directory: 'yolo/darknet/data/coco.names'

### ISSUE THREAD

**Issue by laulau9** [matth200/Fall-detection-with-camera#1]
Bonjour, j'ai une erreur quand je veux lancer detection.py car il semble qu'il manque le fichier "data", comment faire ?
Merci beaucoup

**Comment by matth200** [comment]
Je viens de régler le problème, maintenant tu as juste a clone le projet avec git clone et lancer ./install.sh et tout sera bon.
`~$ git clone https://github.com/matth200/Fall-detection-with-camera.git`
`~$ cd Fall-detection-with-camera`
`~$ chmod +x install.sh`
`~$ ./install.sh`
et après ça tu lances detection.py ou detection_timer.py
