### ISSUE TITLE
annotations mpii_human_pose_v1

### ISSUE THREAD

**Issue by AnthonyKompaiR** [matth200/Fall-detection-with-camera#2]
Bonjour ! 

J'essaye d'utiliser la création de modèle et j'ai pu mettre en place le dataset FPDS mais pour le mpii_human_pose_v1, les annotations du dataset comportent les coordonnées de la bounding box mais aucune notion de chute ou non. 

Je voulais savoir la manière que vous avez utilisé pour compléter les annotations ? Si y a un moyen pour automatiser ou s'il faut le faire à la main ? Voir si vous pourriez les fournir potentiellement ?

Merci beaucoup pour votre temps !

**Comment by matth200** [comment]
Bonjour,

Alors j'ai utilisé le dataset mpii_human_pose_v1 pour ajouter des données à la base de donnée que j'avais initialement,
Comme c'est des activitées en général qui se font debout (pas tombé, ni inconscient), je suis parti de l'hypothése que je les labélisais tous en "pas tombé" pour avoir une plus grande dataset.

C'est pour ça que j'avais créé un script qui créait des fichiers txt du même nom que chaque image avec les coordonées des personnes sur les images et le label "pas tombé" toujours dans le but d'augmenter la base de données.

J'espère que ça répond à tes questions ! 
Hésites pas sinon

**Comment by AnthonyKompaiR** [comment]
Ohhh très bien ! 
Merci pour ta réponse ! 

On peut fermer l'issue du coup !
